# Generated by Django 6.0.4 on 2026-07-15 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(choices=[('pieza', 'Pieza'), ('litro', 'Litro'), ('kg', 'Kilogramo'), ('gramo', 'Gramo'), ('ml', 'Mililitro'), ('par', 'Par'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('rollo', 'Rollo'), ('otro', 'Otro')], default='pieza', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='comparador.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_comparador', to='insumos.proveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='comparador.producto')),
            ],
            options={
                'verbose_name': 'Precio por Proveedor',
                'verbose_name_plural': 'Precios por Proveedor',
                'ordering': ['precio'],
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
