# Generated by Django 6.0.4 on 2026-07-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparador', '0001_initial'),
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='insumo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_comparador', to='insumos.insumo', verbose_name='Insumo vinculado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(blank=True, choices=[('pieza', 'Pieza'), ('litro', 'Litro'), ('kg', 'Kilogramo'), ('gramo', 'Gramo'), ('ml', 'Mililitro'), ('par', 'Par'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('rollo', 'Rollo'), ('otro', 'Otro')], default='pieza', max_length=20),
        ),
    ]
