# Generated by Django 6.0.4 on 2026-07-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('aromatizante', 'Aromatizante'), ('microfibra', 'Microfibra / Esponja'), ('cera', 'Cera / Pulimento'), ('shampoo', 'Shampoo'), ('desengrasante', 'Desengrasante'), ('accesorio', 'Accesorio para Auto'), ('limpiador', 'Limpiador Interior/Exterior'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('unidad', models.CharField(choices=[('pieza', 'Pieza'), ('litro', 'Litro (L)'), ('mililitro', 'Mililitro (mL)'), ('kilo', 'Kilogramo (kg)'), ('par', 'Par'), ('paquete', 'Paquete'), ('kit', 'Kit')], default='pieza', max_length=20)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, help_text='Cuánto te costó a ti (precio de compra al proveedor)', max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, help_text='Precio al que lo vendes al cliente', max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_tienda', to='insumos.proveedor')),
            ],
            options={
                'verbose_name': 'Producto Tienda',
                'verbose_name_plural': 'Productos Tienda',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insumos.proveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='tienda.productotienda')),
            ],
            options={
                'verbose_name': 'Entrada de Producto',
                'verbose_name_plural': 'Entradas de Productos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='tienda.productotienda')),
            ],
            options={
                'verbose_name': 'Venta de Producto',
                'verbose_name_plural': 'Ventas de Productos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
