# Generated by Django 6.0.4 on 2026-07-13 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('limpiador', 'Limpiador'), ('desengrasante', 'Desengrasante'), ('cera', 'Cera / Pulimento'), ('shampoo', 'Shampoo'), ('abrillantador', 'Abrillantador'), ('aromatizante', 'Aromatizante'), ('microfibra', 'Microfibra / Esponja'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('unidad_medida', models.CharField(choices=[('litro', 'Litro (L)'), ('mililitro', 'Mililitro (mL)'), ('kilo', 'Kilogramo (kg)'), ('gramo', 'Gramo (g)'), ('pieza', 'Pieza'), ('galon', 'Galón')], default='litro', max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Alerta si el stock baja de este nivel', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='insumos.proveedor')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='insumos.insumo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insumos.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
