# Generated by Django 6.0.4 on 2026-07-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('prioridad', models.CharField(choices=[('fuego', '🔥 Fuego'), ('pronto', '⚡ Pronto'), ('sinprisa', '🌿 Sin prisa')], default='sinprisa', max_length=10)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
            },
        ),
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libre', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.CharField(blank=True, help_text='Ej: 2 litros, 1 caja, 500 ml', max_length=80)),
                ('prioridad', models.CharField(choices=[('fuego', '🔥 Fuego'), ('pronto', '⚡ Pronto'), ('sinprisa', '🌿 Sin prisa')], default='sinprisa', max_length=10)),
                ('notas', models.CharField(blank=True, max_length=400)),
                ('comprado', models.BooleanField(default=False)),
                ('fecha_compra', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_lista', to='insumos.insumo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_lista', to='insumos.proveedor')),
            ],
            options={
                'verbose_name': 'Item de lista',
                'verbose_name_plural': 'Lista de compras',
            },
        ),
    ]
