# Generated by Django 6.0.4 on 2026-08-14 02:11
# Reordenado a mano para poder migrar los datos existentes (litros/costo unitario)
# hacia el nuevo modelo basado en envases antes de borrar los campos viejos.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def copiar_datos_legacy(apps, schema_editor):
    Insumo = apps.get_model('insumos', 'Insumo')
    Compra = apps.get_model('insumos', 'Compra')

    for insumo in Insumo.objects.all():
        contenido = float(insumo.contenido_envase or 1) or 1
        insumo.costo_envase = insumo.costo_unitario or 0
        insumo.envases_en_bodega = int(round(float(insumo.stock_actual or 0) / contenido))
        insumo.envases_stock_minimo = int(round(float(insumo.stock_minimo or 0) / contenido))
        insumo.save(update_fields=['costo_envase', 'envases_en_bodega', 'envases_stock_minimo'])

    for compra in Compra.objects.all():
        compra.envases = max(1, int(round(float(compra.cantidad or 1))))
        compra.costo_por_envase = compra.costo_unitario or 0
        compra.save(update_fields=['envases', 'costo_por_envase'])


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_add_lista_compras_recordatorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='costo_por_envase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='envases',
            field=models.PositiveIntegerField(default=1, help_text='Cuántos envases compraste'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='contenido_envase',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Cuánto trae cada envase, en la unidad de medida (ej: 1 para un bote de 1 litro)', max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='costo_envase',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de un envase nuevo — se actualiza solo con la última compra', max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='costo_estimado_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo por servicio mientras no haya historial de rendimiento (opcional)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='envases_en_bodega',
            field=models.PositiveIntegerField(default=0, help_text='Envases cerrados, sin abrir, guardados'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='envases_stock_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Alerta si los envases en bodega bajan de este nivel'),
        ),
        migrations.CreateModel(
            name='EnvaseEnUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('costo_envase', models.DecimalField(decimal_places=2, help_text='Costo del envase al momento de abrirlo', max_digits=10)),
                ('vehiculos_atendidos', models.PositiveIntegerField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envases_uso', to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Envase en Uso',
                'verbose_name_plural': 'Envases en Uso',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.RunPython(copiar_datos_legacy, revertir),
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='costo_unitario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='costo_unitario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='stock_minimo',
        ),
    ]
