# Generated by Django 6.0.4 on 2026-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_remove_compra_cantidad_remove_compra_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envaseenuso',
            name='contenido_envase',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Contenido del envase al momento de abrirlo, en la unidad de medida del insumo', max_digits=10),
        ),
    ]
