# Generated by Django 6.0.4 on 2026-07-13 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('precio_cobrado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('multiplicador_precio', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador sobre el precio base (ej: 1.5 = 50% más caro)', max_digits=4)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleInsumoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=3, max_digits=8)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_insumos', to='servicios.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.tiposervicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.tipovehiculo'),
        ),
        migrations.CreateModel(
            name='InsumoEnServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_servicio', models.DecimalField(decimal_places=3, help_text='Cantidad de insumo usada por servicio', max_digits=8)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_que_usan', to='insumos.insumo')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_requeridos', to='servicios.tiposervicio')),
            ],
            options={
                'verbose_name': 'Insumo en Servicio',
                'verbose_name_plural': 'Insumos en Servicios',
                'unique_together': {('tipo_servicio', 'insumo')},
            },
        ),
    ]
