# Generated by Django 6.0.4 on 2026-07-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='costo_insumos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo estimado de insumos usados en este servicio', max_digits=8),
        ),
    ]
