# Generated by Django 6.0.4 on 2026-08-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_cliente_servicio_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de Servicio', 'verbose_name_plural': 'Tipos de Servicio'},
        ),
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de Vehículo', 'verbose_name_plural': 'Tipos de Vehículo'},
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='multiplicador_precio',
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden en que se muestra (Paquete 1, 2...)'),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Orden en que se muestra (chico a grande)'),
        ),
        migrations.CreateModel(
            name='PrecioPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='servicios.tiposervicio')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='servicios.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Precio de Paquete',
                'verbose_name_plural': 'Precios de Paquetes',
                'ordering': ['tipo_servicio', 'tipo_vehiculo'],
                'unique_together': {('tipo_servicio', 'tipo_vehiculo')},
            },
        ),
    ]
