# Generated by Django 6.0.4 on 2026-08-14 02:11
# Reordenado a mano para migrar InsumoEnServicio hacia el nuevo M2M TipoServicio.insumos
# antes de borrar el modelo viejo.

from django.db import migrations, models


def copiar_insumos_legacy(apps, schema_editor):
    InsumoEnServicio = apps.get_model('servicios', 'InsumoEnServicio')
    for rel in InsumoEnServicio.objects.all():
        rel.tipo_servicio.insumos.add(rel.insumo)


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_remove_compra_cantidad_remove_compra_costo_unitario_and_more'),
        ('servicios', '0005_paquetes_neowash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='insumos',
            field=models.ManyToManyField(blank=True, help_text='Productos que se usan en este paquete', related_name='tipos_servicio', to='insumos.insumo'),
        ),
        migrations.RunPython(copiar_insumos_legacy, revertir),
        migrations.AlterUniqueTogether(
            name='insumoenservicio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='insumoenservicio',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='insumoenservicio',
            name='tipo_servicio',
        ),
        migrations.DeleteModel(
            name='DetalleInsumoServicio',
        ),
        migrations.DeleteModel(
            name='InsumoEnServicio',
        ),
    ]
