# Generated by Django 6.0.4 on 2026-08-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_envaseenuso_contenido_envase'),
        ('servicios', '0006_alter_insumoenservicio_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='es_cortesia',
            field=models.BooleanField(default=False, help_text='Servicio de cortesía: no cuenta en ingresos/ganancia, pero sí gasta insumo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='insumos_usados',
            field=models.ManyToManyField(blank=True, help_text='Productos realmente usados en este servicio (por defecto, los del paquete)', related_name='servicios_usados', to='insumos.insumo'),
        ),
    ]
