# Generated by Django 6.0.4 on 2026-08-14 01:02

import django.db.models.deletion
import django.utils.timezone
import recepcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_add_lealtad_fields'),
        ('servicios', '0003_servicio_cliente_servicio_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_recepcion', models.TimeField(default=recepcion.models._hora_actual)),
                ('lugar', models.CharField(choices=[('negocio', 'En negocio'), ('domicilio', 'Recogido a domicilio')], default='negocio', max_length=10)),
                ('cliente_nombre', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('forma_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=15)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('tipo_vehiculo_txt', models.CharField(blank=True, choices=[('moto', 'Moto'), ('auto_chico', 'Auto Pequeño'), ('sedan', 'Sedán / Auto Mediano'), ('pickup', 'Pick Up'), ('camioneta', 'Camioneta / SUV'), ('van', 'Van / Minivan'), ('camion', 'Camión')], max_length=20)),
                ('km', models.PositiveIntegerField(blank=True, null=True)),
                ('gasolina', models.CharField(blank=True, choices=[('R', 'R'), ('1_4', '¼'), ('1_2', '½'), ('3_4', '¾'), ('lleno', 'Lleno')], max_length=6)),
                ('paquete', models.CharField(blank=True, choices=[('neo_express', 'Neo Express'), ('neo_completo', 'Neo Completo')], max_length=20)),
                ('entrega', models.CharField(choices=[('recoge', 'Pasa a recoger'), ('domicilio', 'Domicilio')], default='recoge', max_length=10)),
                ('direccion_entrega', models.TextField(blank=True)),
                ('diagrama_danos', models.JSONField(blank=True, default=dict)),
                ('retiro_valores', models.BooleanField(default=False)),
                ('obs_cliente', models.TextField(blank=True)),
                ('obs_colaborador', models.TextField(blank=True)),
                ('firma_cliente', models.TextField(blank=True)),
                ('firma_colaborador', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='clientes.cliente')),
                ('servicio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepcion', to='servicios.servicio')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='clientes.vehiculo')),
            ],
            options={
                'verbose_name': 'Recepción',
                'verbose_name_plural': 'Recepciones',
                'ordering': ['-fecha', '-hora_recepcion'],
            },
        ),
    ]
