# Generated by Django 6.0.4 on 2026-08-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='diagrama_tipo',
            field=models.CharField(choices=[('sedan', 'Sedán'), ('pickup', 'Pick Up')], default='sedan', max_length=10),
        ),
    ]
