# Generated by Django 6.0.4 on 2026-08-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_recepcion_diagrama_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='diagrama_tipo',
            field=models.CharField(choices=[('sedan', 'Sedán'), ('suv', 'SUV / Camioneta'), ('pickup', 'Pick Up')], default='sedan', max_length=10),
        ),
    ]
