# Generated by Django 6.0.4 on 2026-08-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_alter_recepcion_diagrama_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion',
            name='paquete',
        ),
    ]
