# Generated by Django 6.0.4 on 2026-07-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('gris', 'Gris'), ('plata', 'Plata'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('naranja', 'Naranja'), ('cafe', 'Café / Beige'), ('morado', 'Morado'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('tipo', models.CharField(choices=[('moto', 'Moto'), ('auto_chico', 'Auto Pequeño'), ('sedan', 'Sedán / Auto Mediano'), ('pickup', 'Pick Up'), ('camioneta', 'Camioneta / SUV'), ('van', 'Van / Minivan'), ('camion', 'Camión')], default='sedan', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
    ]
