# Generated by Django 6.0.4 on 2026-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultimo_premio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='visitas_lealtad',
            field=models.IntegerField(default=0),
        ),
    ]
