# Generated by Django 6.0.4 on 2026-08-17 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(help_text='Ej: Descontaminación de cristales, Pulido de faros...', max_length=100)),
                ('notas', models.TextField(blank=True, help_text='Detalle de por qué le serviría (opcional)')),
                ('atendida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Oportunidad de Cliente',
                'verbose_name_plural': 'Oportunidades de Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
