# Generated by Django 6.0.4 on 2026-08-17 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_oportunidadcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadcliente',
            name='vehiculo',
            field=models.ForeignKey(blank=True, help_text='El vehículo específico que necesita el servicio/producto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='clientes.vehiculo'),
        ),
    ]
